<a href="https://colab.research.google.com/github/profteachkids/STEMUnleashed2023/blob/main/LinearAndNonLinearRegressionAntoineEquation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
!wget https://raw.githubusercontent.com/profteachkids/STEMUnleashed2023/main/WaterVaporPressure.csv -O WaterVaporPressure.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [18]:
import numpy as np
from plotly.subplots import make_subplots
from scipy.optimize import minimize

In [10]:
data=np.loadtxt("WaterVaporPressure.csv",delimiter=',')

In [11]:
T_exp, Pvap_exp=data.T

In [12]:
V=np.c_[T_exp, -np.log10(Pvap_exp), np.ones_like(T_exp)]

In [13]:
A, C, D = np.linalg.solve(V.T @ V, V.T @ ((T_exp * np.log10(Pvap_exp)).reshape(-1,1)))
B = A*C - D

In [17]:
A, B, C

(array([10.22799112]), array([1771.95510013]), array([-34.37892593]))

In [28]:
def sse(v):
    A,B,C = v
    Log10Pmodel = (A-B/(T_exp+C))
    return np.sum((np.log10(Pvap_exp)-Log10Pmodel)/**2)

In [29]:
minimize(sse, np.array([10.23, 1770, -34.4]))

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 0.0005625866346110625
        x: [ 1.023e+01  1.770e+03 -3.461e+01]
      nit: 5
      jac: [ 2.670e-08  3.530e-06  3.420e-07]
 hess_inv: [[ 7.377e-02  4.689e-01 -4.870e+00]
            [ 4.689e-01  4.999e+00 -4.166e+01]
            [-4.870e+00 -4.166e+01  4.349e+02]]
     nfev: 40
     njev: 10

In [16]:
x_plot=np.linspace(T_exp.min(), T_exp.max(), 100)
fig = make_subplots()
fig.add_scatter(x=T_exp, y=Pvap_exp, mode='markers')
fig.add_scatter(x=x_plot, y=10**(A-B/(x_plot+C)), mode='lines')
fig

In [15]:
fig