<a href="https://colab.research.google.com/github/profteachkids/STEMUnleashed2023/blob/main/LinearAndNonLinearRegressionAntoineEquation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!wget https://raw.githubusercontent.com/profteachkids/STEMUnleashed2023/main/WaterVaporPressure.csv -O WaterVaporPressure.csv

--2023-06-21 12:23:06--  https://raw.githubusercontent.com/profteachkids/STEMUnleashed2023/main/WaterVaporPressure.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1300 (1.3K) [text/plain]
Saving to: ‘WaterVaporPressure.csv’

WaterVaporPressure. 100%[===================>]   1.27K  --.-KB/s    in 0s      

2023-06-21 12:23:06 (38.0 MB/s) - ‘WaterVaporPressure.csv’ saved [1300/1300]



In [1]:
import numpy as np
from plotly.subplots import make_subplots
from scipy.optimize import minimize

In [5]:
data=np.loadtxt("WaterVaporPressure.csv",delimiter=',')

In [6]:
T_exp, Pvap_exp=data.T

In [14]:
V=np.c_[T_exp, -np.log10(Pvap_exp), np.ones_like(T_exp)]

In [15]:
A, C, D = np.linalg.solve(V.T @ V, V.T @ ((T_exp * np.log10(Pvap_exp)).reshape(-1,1)))
B = A*C - D

In [16]:
A, B, C

(array([10.22799112]), array([1771.95510013]), array([-34.37892593]))

In [13]:
def sse(v):
    A,B,C = v
    Log10Pmodel = (A-B/(T_exp+C))
    return np.sum((np.log10(Pvap_exp)-Log10Pmodel)**2)

In [14]:
minimize(sse, np.array([10.23, 1770, -34.4]))

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 0.0005625866346110625
        x: [ 1.023e+01  1.770e+03 -3.461e+01]
      nit: 5
      jac: [ 2.670e-08  3.530e-06  3.420e-07]
 hess_inv: [[ 7.377e-02  4.689e-01 -4.870e+00]
            [ 4.689e-01  4.999e+00 -4.166e+01]
            [-4.870e+00 -4.166e+01  4.349e+02]]
     nfev: 40
     njev: 10

In [20]:
x_plot=np.linspace(T_exp.min(), T_exp.max(),100)
fig = make_subplots()
fig.add_scatter(x=T_exp, y=Pvap_exp,mode='markers')
fig.add_scatter(x=x_plot, y=10**(A-B/(x_plot+C)), mode='lines')
fig.update_yaxes(type='log')
fig.update_layout(width=600,height=500,template='plotly_dark')

In [16]:
T_exp

array([293.15, 303.15, 313.15, 323.15, 333.15, 343.15, 412.75, 432.85,
       451.25, 463.15, 473.35, 482.55, 492.65, 504.15, 507.77, 521.28,
       535.18, 541.49, 552.6 , 557.97, 561.69, 571.31, 645.95, 646.04,
       646.07, 647.09])

In [17]:
Pvap_exp

array([2.4000e+03, 4.2660e+03, 7.3330e+03, 1.2332e+04, 1.9932e+04,
       3.1224e+04, 3.5700e+05, 6.1300e+05, 9.6000e+05, 1.2550e+06,
       1.5620e+06, 1.8850e+06, 2.2980e+06, 2.8500e+06, 3.0430e+06,
       3.8540e+06, 4.8510e+06, 5.3640e+06, 6.3660e+06, 6.8990e+06,
       7.2880e+06, 8.3710e+06, 2.1674e+07, 2.1794e+07, 2.1804e+07,
       2.1336e+07])